repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        files: "^(?!examples/)"
        args: ["--application-directories=gen"]
        exclude: "^files/"

  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        files: "^gen/"
        args: ["-S"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "^gen/tests/data/"
